ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - protobufjs
  - supabase
  - unrs-resolver

onlyBuiltDependencies:
  - '@firebase/util'
